#!/bin/bash
#PBS -N benchcab-ilamb
#PBS -l wd
#PBS -P tm70
#PBS -q normal
#PBS -l walltime=1:00:00  
#PBS -l ncpus=16
#PBS -l mem=32GB
#PBS -l storage=gdata/hh5+gdata/ct11

module use /g/data/hh5/public/modules
module load conda/analysis3-23.01

export ILAMB_ROOT=`realpath ILAMB_ROOT`

mpiexec -n $PBS_NCPUS ilamb-run \
  --config cable.cfg \
  --model_root $ILAMB_ROOT/MODELS/ \
  --regions global \
  --model_year 1903 1984 \
